## Syntax highlighting for Makefiles.

## This file was modified by Mikhail Shprygov
## For contact find me on github.com/mshprygov

#syntax makefile "(^|/)((GNU)?m|M)akefile[^/]*$|\.(make|mk)$"
syntax makefile "(^|/)((GNU)?m|M)akefile$|\.(make|mk)$"
magic "makefile script"

tabgives "	"
comment "#"

# Targets, special symbols and punctuation.
#color brightgreen "%"
#color brightgreen "@"
color brightblue "^[A-Za-z0-9_./%()-]+[[:space:]]*:([^=]|$)"
color brightblue "[:;]"
color blue "\\$"
color cyan "^	[@-][a-zA-Z0-9_-]+?"

# Built-in special targets.
color brightred "\.\<(DEFAULT|IGNORE|SILENT|DELETE_ON_ERROR|EXPORT_ALL_VARIABLES|PRECIOUS|SECONDARY|NOTPARALLEL)\>"

# .PHONY
color blue "\.\<PHONY\>"

# Assignments.
color yellow " (:?:|\+|\?)?= "

# Keywords.
color green "^[[:space:]]*(-include|sinclude|include|if|ifn?def|ifn?eq|else|endif)\>"
color green "\<(override|(un)?define|endef|(un)?export|private|vpath)\>"

# Fix whatever is inside the quotes and parenthesis.
color normal ""[^"]*""
color normal "\([^)]*\)"

# Variable expansions.
color brightgreen "\$+[{(][a-zA-Z0-9_-]+[})]"
color brightgreen "\$+[@^<$?*]?"

# Compiler flags.
#color green "\s-[DILloOSv]"

# Native text utilities.
color green "\<(addprefix|filter)\>"

# Bash flow control.
color green "\<(for|in|do|done|then|if|else|fi|while|case|esac)\>"

# Comments.
color magenta "(^|[[:blank:]]+)#.*"

# Trailing whitespace.
color ,green "[[:space:]]+$"
